In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from spellchecker import SpellChecker
import numpy as np

# Load the dataset
data = pd.read_csv("newdata.csv")
data

,sentences,grammar label,spelling label
0,She do not like the how to write the novels.,1,1
1,They're going too their hom.,1,1
2,He are going two the store.,1,1
3,I seen that movie yesterday.,1,1
4,She writed a letter to her friend.,1,1
...,...,...,...
195,He studies architecture at college.,0,0
196,They adopt rescue animals from shelters.,0,0
197,I enjoy painting landscapes.,0,0
198,She plays the violin in a symphony orchestra.,0,0
199,He writes articles for a newspaper.,0,0

In [73]:
import pandas as pd
import random
import numpy as np

# Sample sentences (a mix of correct, spelling errors, and grammar errors)
correct_sentences = [
    "The cat sat on the mat.",
    "She sells seashells by the seashore.",
    "I am learning data science.",
    "He quickly realized his mistake.",
    "We are going to the park."
]

spelling_error_sentences = [
    "The kat sat on the mat.",
    "She sells seashels by the seashore.",
    "I am lernig data science.",
    "He quikly realized his mistake.",
    "We are going to the prk."
]

grammar_error_sentences = [
    "The cat sat on mat.",
    "She sell seashells by the seashore.",
    "I learning data science.",
    "He quickly realize his mistake.",
    "We going to the park."
]

# Function to create a mixed dataset
#def create_dataset(num_sentences=1000):
    sentences = []
    spelling_labels = []
    grammar_labels = []
    
    for _ in range(num_sentences):
        sentence_type = random.choice(['correct', 'spelling', 'grammar', 'both'])
        
        if sentence_type == 'correct':
            sentence = random.choice(correct_sentences)
            spelling_label = 0
            grammar_label = 0
        elif sentence_type == 'spelling':
            sentence = random.choice(spelling_error_sentences)
            spelling_label = 1
            grammar_label = 0
        elif sentence_type == 'grammar':
            sentence = random.choice(grammar_error_sentences)
            spelling_label = 0
            grammar_label = 1
        elif sentence_type == 'both':
            sentence = random.choice(spelling_error_sentences)
            sentence = sentence.replace(' ', ' ', 1)  # Introduce a minor grammar error in a spelling error sentence
            spelling_label = 1
            grammar_label = 1
        
        sentences.append(sentence)
        spelling_labels.append(spelling_label)
        grammar_labels.append(grammar_label)
    
    df = pd.DataFrame({
        'sentence': sentences,
        'spell_error_label': spelling_labels,
        'grammar_error_label': grammar_labels
    })
    
    df['spellcount'] = df['spell_error_label'].sum()
    
    return df

# Create the dataset
df = create_dataset(1000)

# Save to CSV
df.to_csv('new_error_dataset.csv', index=False)

print("new_error_dataset.csv'")

new_error_dataset.csv'

In [76]:
import random
import pandas as pd
import numpy as np

# List of sample words to create sentences
words = ["this", "is", "a", "sample", "sentence", "with", "some", "random", "words"]

# Function to introduce spelling errors in a sentence
def introduce_spelling_errors(sentence, error_rate=0.1):
    words = sentence.split()
    num_errors = int(len(words) * error_rate)
    error_indices = random.sample(range(len(words)), num_errors)
    for i in error_indices:
        word = words[i]
        if len(word) > 1:
            swap_idx = random.randint(0, len(word) - 2)
            words[i] = word[:swap_idx] + word[swap_idx+1] + word[swap_idx] + word[swap_idx+2:]
    return ' '.join(words), len(error_indices)

# Function to introduce grammar errors in a sentence
def introduce_grammar_errors(sentence, error_rate=0.1):
    words = sentence.split()
    num_errors = int(len(words) * error_rate)
    error_indices = random.sample(range(len(words)), num_errors)
    for i in error_indices:
        if i < len(words) - 1:
            words[i], words[i+1] = words[i+1], words[i]
    return ' '.join(words)

# Generate random sentences
def generate_random_sentence():
    return ' '.join(random.choices(words, k=random.randint(5, 10)))

# Create the dataset
data = []
num_sentences = 1000

for _ in range(num_sentences):
    sentence = generate_random_sentence()
    
    spell_error = random.choice([0, 1])
    grammar_error = random.choice([0, 1])
    
    if spell_error:
        sentence, spell_count = introduce_spelling_errors(sentence)
    else:
        spell_count = 0
    
    if grammar_error:
        sentence = introduce_grammar_errors(sentence)
    
    data.append([sentence, spell_error, grammar_error, spell_count])

# Convert to DataFrame
df1 = pd.DataFrame(data, columns=['sentence', 'spelling_label', 'grammar_label', 'no_of_spell_errors'])

# Save to CSV
df1.to_csv('specialdataset.csv', index=False)

print("specialdataset.csv'.")

specialdataset.csv'.

In [5]:
data = pd.read_csv("newdata.csv")
data

,sentences,grammar label,spelling label
0,She do not like the how to write the novels.,1,1
1,They're going too their hom.,1,1
2,He are going two the store.,1,1
3,I seen that movie yesterday.,1,1
4,She writed a letter to her friend.,1,1
...,...,...,...
195,He studies architecture at college.,0,0
196,They adopt rescue animals from shelters.,0,0
197,I enjoy painting landscapes.,0,0
198,She plays the violin in a symphony orchestra.,0,0
199,He writes articles for a newspaper.,0,0

In [40]:
df=pd.DataFrame(data)
df

,sentences,grammar label,spelling label
0,She do not like the how to write the novels.,1,1
1,They're going too their hom.,1,1
2,He are going two the store.,1,1
3,I seen that movie yesterday.,1,1
4,She writed a letter to her friend.,1,1
...,...,...,...
195,He studies architecture at college.,0,0
196,They adopt rescue animals from shelters.,0,0
197,I enjoy painting landscapes.,0,0
198,She plays the violin in a symphony orchestra.,0,0
199,He writes articles for a newspaper.,0,0

In [ ]:
df

In [ ]:
#df[df['spelling_label']==1]

In [8]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Text preprocessing function
def preprocess_text(sentence):
    # Tokenization
    words = word_tokenize(sentence)
    # Lowercasing
    words = [word.lower() for word in words]
    # Removing punctuation and special characters
    words = [word for word in words if word.isalnum()]
    # Removing stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]
    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word) for word in words]
    return ' '.join(words)

# Apply preprocessing
df['cleaned_sentence'] = df['sentences'].apply(preprocess_text)
print(df[['sentences', 'cleaned_sentence']])

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ganes\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ganes\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ganes\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

                                         sentences  \
0     She do not like the how to write the novels.
1                     They're going too their hom.
2                      He are going two the store.
3                     I seen that movie yesterday.
4               She writed a letter to her friend.
..                                             ...
195            He studies architecture at college.
196       They adopt rescue animals from shelters.
197                   I enjoy painting landscapes.
198  She plays the violin in a symphony orchestra.
199            He writes articles for a newspaper.

                   cleaned_sentence
0                  like write novel
1                         going hom
2                   going two store
3              seen movie yesterday
4              writed letter friend
..                              ...
195      study architecture college
196     adopt rescue animal shelter
197        enjoy painting landscape
198  play violin symphony orchestra
199        writes article newspaper

[200 rows x 2 columns]

In [41]:
df

,sentences,grammar label,spelling label
0,She do not like the how to write the novels.,1,1
1,They're going too their hom.,1,1
2,He are going two the store.,1,1
3,I seen that movie yesterday.,1,1
4,She writed a letter to her friend.,1,1
...,...,...,...
195,He studies architecture at college.,0,0
196,They adopt rescue animals from shelters.,0,0
197,I enjoy painting landscapes.,0,0
198,She plays the violin in a symphony orchestra.,0,0
199,He writes articles for a newspaper.,0,0

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Vectorize the cleaned sentences using TF-IDF
vectorizer = TfidfVectorizer(max_features=5000)  # Adjust max_features as needed
X = vectorizer.fit_transform(df['sentences']).toarray()

# Combine with original labels
y_spelling = df['spelling label']
y_grammar = df['grammar label']

In [44]:
y_spelling.value_counts()

0    153
1     47
Name: spelling label, dtype: int64

In [45]:
y_grammar.value_counts()

0    116
1     84
Name: grammar label, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train_spelling, y_test_spelling, y_train_grammar, y_test_grammar = train_test_split(
    X, y_spelling, y_grammar, test_size=0.2, random_state=42)

# Train a Logistic Regression model for spelling error detection
model_spelling = LogisticRegression()
model_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
model_grammar = LogisticRegression()
model_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
y_pred_spelling = model_spelling.predict(X_test)
y_pred_grammar = model_grammar.predict(X_test)

# Evaluate the models
print("Spelling Error Detection:")
print(classification_report(y_test_spelling, y_pred_spelling))
print("Accuracy:", accuracy_score(y_test_spelling, y_pred_spelling))

print("Grammar Error Detection:")
print(classification_report(y_test_grammar, y_pred_grammar))
print("Accuracy:", accuracy_score(y_test_grammar, y_pred_grammar))

Spelling Error Detection:
              precision    recall  f1-score   support

           0       0.80      1.00      0.89        32
           1       0.00      0.00      0.00         8

    accuracy                           0.80        40
   macro avg       0.40      0.50      0.44        40
weighted avg       0.64      0.80      0.71        40

Accuracy: 0.8
Grammar Error Detection:
              precision    recall  f1-score   support

           0       0.58      0.78      0.67        23
           1       0.44      0.24      0.31        17

    accuracy                           0.55        40
   macro avg       0.51      0.51      0.49        40
weighted avg       0.52      0.55      0.51        40

Accuracy: 0.55

C:\Users\ganes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ganes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ganes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [47]:
from sklearn.tree import DecisionTreeClassifier

In [48]:
from sklearn.neighbors import KNeighborsClassifier

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
maxAcc_spell=0
maxAcc_gram=0
maxRs=0
for i in range(1,400):
    X_train, X_test, y_train_spelling, y_test_spelling, y_train_grammar, y_test_grammar = train_test_split(
    X, y_spelling, y_grammar, test_size=0.2, random_state=i)

# Initialize and fit RandomForestClassifier
    model_spelling = LogisticRegression()
    model_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    model_grammar = LogisticRegression()
    model_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
    y_pred_spelling = model_spelling.predict(X_test)
    y_pred_grammar = model_grammar.predict(X_test)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
    
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
    
    if acc_spell>maxAcc_spell and acc_grammar>maxAcc_gram:
        maxAcc_spell=acc_spell
        maxAcc_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for the sampled data is spell accuracy {maxAcc_spell}, grammar accuracy {maxAcc_gram} and randomstate is{maxRs}')

Best Accuracy for the sampled data is spell accuracy 0.9, grammar accuracy 0.7 and randomstate is208

In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
maxAcc_spell=0
maxAcc_gram=0
maxRs=0
for i in range(1,400):
    X_train, X_test, y_train_spelling, y_test_spelling, y_train_grammar, y_test_grammar = train_test_split(
    X, y_spelling, y_grammar, test_size=0.2, random_state=i)

# Initialize and fit RandomForestClassifier
    model_spelling = RandomForestClassifier()
    model_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    model_grammar = RandomForestClassifier()
    model_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
    y_pred_spelling = model_spelling.predict(X_test)
    y_pred_grammar = model_grammar.predict(X_test)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
    
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
    
    if acc_spell>maxAcc_spell and acc_grammar>maxAcc_gram:
        maxAcc_spell=acc_spell
        maxAcc_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for the sampled data is spell accuracy {maxAcc_spell}, grammar accuracy {maxAcc_gram} and randomstate is{maxRs}')

Best Accuracy for the sampled data is spell accuracy 0.825, grammar accuracy 0.65 and randomstate is147

In [51]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
maxAcc_spell=0
maxAcc_gram=0
maxRs=0
for i in range(1,400):
    X_train, X_test, y_train_spelling, y_test_spelling, y_train_grammar, y_test_grammar = train_test_split(
    X, y_spelling, y_grammar, test_size=0.2, random_state=i)

# Initialize and fit RandomForestClassifier
    model_spelling = DecisionTreeClassifier()
    model_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    model_grammar = DecisionTreeClassifier()
    model_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
    y_pred_spelling = model_spelling.predict(X_test)
    y_pred_grammar = model_grammar.predict(X_test)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
    
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
    
    if acc_spell>maxAcc_spell and acc_grammar>maxAcc_gram:
        maxAcc_spell=acc_spell
        maxAcc_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for the sampled data is spell accuracy {maxAcc_spell}, grammar accuracy {maxAcc_gram} and randomstate is{maxRs}')

Best Accuracy for the sampled data is spell accuracy 0.775, grammar accuracy 0.65 and randomstate is8

In [52]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
maxAcc_spell=0
maxAcc_gram=0
maxRs=0
for i in range(1,400):
    X_train, X_test, y_train_spelling, y_test_spelling, y_train_grammar, y_test_grammar = train_test_split(
    X, y_spelling, y_grammar, test_size=0.2, random_state=i)

# Initialize and fit RandomForestClassifier
    model_spelling = KNeighborsClassifier()
    model_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    model_grammar = KNeighborsClassifier()
    model_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
    y_pred_spelling = model_spelling.predict(X_test)
    y_pred_grammar = model_grammar.predict(X_test)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
    
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
    
    if acc_spell>maxAcc_spell and acc_grammar>maxAcc_gram:
        maxAcc_spell=acc_spell
        maxAcc_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for the sampled data is spell accuracy {maxAcc_spell}, grammar accuracy {maxAcc_gram} and randomstate is{maxRs}')

Best Accuracy for the sampled data is spell accuracy 0.85, grammar accuracy 0.5 and randomstate is153

In [53]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
maxAcc_spell=0
maxAcc_gram=0
maxRs=0
for i in range(1,400):
    X_train, X_test, y_train_spelling, y_test_spelling, y_train_grammar, y_test_grammar = train_test_split(
    X, y_spelling, y_grammar, test_size=0.2, random_state=i)

# Initialize and fit RandomForestClassifier
    model_spelling = SVC()
    model_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    model_grammar = SVC(kernel='linear')
    model_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
    y_pred_spelling = model_spelling.predict(X_test)
    y_pred_grammar = model_grammar.predict(X_test)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
    
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
    
    if acc_spell>maxAcc_spell and acc_grammar>maxAcc_gram:
        maxAcc_spell=acc_spell
        maxAcc_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for the sampled data is spell accuracy {maxAcc_spell}, grammar accuracy {maxAcc_gram} and randomstate is{maxRs}')

Best Accuracy for the sampled data is spell accuracy 0.875, grammar accuracy 0.625 and randomstate is8

In [54]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
maxAcc_spell=0
maxAcc_gram=0
maxRs=0
for i in range(1,400):
    X_train, X_test, y_train_spelling, y_test_spelling, y_train_grammar, y_test_grammar = train_test_split(
    X, y_spelling, y_grammar, test_size=0.2, random_state=i)

# Initialize and fit RandomForestClassifier
    model_spelling = GradientBoostingClassifier()
    model_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    model_grammar = GradientBoostingClassifier()
    model_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
    y_pred_spelling = model_spelling.predict(X_test)
    y_pred_grammar = model_grammar.predict(X_test)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
    
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
    
    if acc_spell>maxAcc_spell and acc_grammar>maxAcc_gram:
        maxAcc_spell=acc_spell
        maxAcc_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for the sampled data is spell accuracy {maxAcc_spell}, grammar accuracy {maxAcc_gram} and randomstate is{maxRs}')

Best Accuracy for the sampled data is spell accuracy 0.8, grammar accuracy 0.7 and randomstate is197

In [55]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
maxAcc_spell=0
maxAcc_gram=0
maxRs=0
for i in range(1,400):
    X_train, X_test, y_train_spelling, y_test_spelling, y_train_grammar, y_test_grammar = train_test_split(
    X, y_spelling, y_grammar, test_size=0.2, random_state=i)

# Initialize and fit RandomForestClassifier
    model_spelling = AdaBoostClassifier(algorithm='SAMME')
    model_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    model_grammar = AdaBoostClassifier(algorithm='SAMME')
    model_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
    y_pred_spelling = model_spelling.predict(X_test)
    y_pred_grammar = model_grammar.predict(X_test)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
    
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
    
    if acc_spell>maxAcc_spell and acc_grammar>maxAcc_gram:
        maxAcc_spell=acc_spell
        maxAcc_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for the sampled data is spell accuracy {maxAcc_spell}, grammar accuracy {maxAcc_gram} and randomstate is{maxRs}')

Best Accuracy for the sampled data is spell accuracy 0.875, grammar accuracy 0.65 and randomstate is8

# scenario2: getting into oversampling

In [56]:
from imblearn.over_sampling import SMOTE
smt=SMOTE()

In [57]:
X_sampled_spelling, y_spelling_sampled = smt.fit_resample(X, y_spelling)
X_sampled_grammar, y_grammar_sampled = smt.fit_resample(X, y_grammar)

In [58]:
# Split for spelling task
X_train_spelling, X_test_spelling, y_train_spelling, y_test_spelling = train_test_split(X_sampled_spelling, y_spelling_sampled, test_size=0.2, random_state=42)

# Split for grammar task
X_train_grammar, X_test_grammar, y_train_grammar, y_test_grammar = train_test_split(X_sampled_grammar, y_grammar_sampled, test_size=0.2, random_state=42)

In [59]:
# Example of training and evaluating models (replace with your model and evaluation process)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Initialize models
model_spelling = RandomForestClassifier(random_state=42)
model_grammar = RandomForestClassifier(random_state=42)

# Train models
model_spelling.fit(X_train_spelling, y_train_spelling)
model_grammar.fit(X_train_grammar, y_train_grammar)

# Predictions
y_pred_spelling = model_spelling.predict(X_test_spelling)
y_pred_grammar = model_grammar.predict(X_test_grammar)

# Evaluate accuracy
accuracy_spelling = accuracy_score(y_test_spelling, y_pred_spelling)
accuracy_grammar = accuracy_score(y_test_grammar, y_pred_grammar)

print(f"Spelling Accuracy: {accuracy_spelling}")
print(f"Grammar Accuracy: {accuracy_grammar}")

Spelling Accuracy: 0.7258064516129032
Grammar Accuracy: 0.574468085106383

In [60]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
maxAcc_spell=0
maxAcc_gram=0
maxRs=0
for i in range(1,400):
    X_train_spelling, X_test_spelling, y_train_spelling, y_test_spelling = train_test_split(X_sampled_spelling, y_spelling_sampled, test_size=0.2, random_state=i)

# Split for grammar task
    X_train_grammar, X_test_grammar, y_train_grammar, y_test_grammar = train_test_split(X_sampled_grammar, y_grammar_sampled, test_size=0.2, random_state=i)


# Initialize and fit RandomForestClassifier
    model_spelling = KNeighborsClassifier()
    model_spelling.fit(X_train_spelling, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    model_grammar = KNeighborsClassifier()
    model_grammar.fit(X_train_grammar, y_train_grammar)

# Predict on the test set
    y_pred_spelling = model_spelling.predict(X_test_spelling)
    y_pred_grammar = model_grammar.predict(X_test_grammar)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
    
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
    
    if acc_spell>maxAcc_spell and acc_grammar>maxAcc_gram:
        maxAcc_spell=acc_spell
        maxAcc_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for the sampled data is spell accuracy {maxAcc_spell}, grammar accuracy {maxAcc_gram} and randomstate is{maxRs}')

Best Accuracy for the sampled data is spell accuracy 0.5645161290322581, grammar accuracy 0.574468085106383 and randomstate is4

In [61]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
maxAcc_spell=0
maxAcc_gram=0
maxRs=0
for i in range(1,400):
    X_train_spelling, X_test_spelling, y_train_spelling, y_test_spelling = train_test_split(X_sampled_spelling, y_spelling_sampled, test_size=0.2, random_state=i)

# Split for grammar task
    X_train_grammar, X_test_grammar, y_train_grammar, y_test_grammar = train_test_split(X_sampled_grammar, y_grammar_sampled, test_size=0.2, random_state=i)


# Initialize and fit RandomForestClassifier
    model_spelling = DecisionTreeClassifier()
    model_spelling.fit(X_train_spelling, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    model_grammar = DecisionTreeClassifier()
    model_grammar.fit(X_train_grammar, y_train_grammar)

# Predict on the test set
    y_pred_spelling = model_spelling.predict(X_test_spelling)
    y_pred_grammar = model_grammar.predict(X_test_grammar)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
    
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
    
    if acc_spell>maxAcc_spell and acc_grammar>maxAcc_gram:
        maxAcc_spell=acc_spell
        maxAcc_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for the sampled data is spell accuracy {maxAcc_spell}, grammar accuracy {maxAcc_gram} and randomstate is{maxRs}')

Best Accuracy for the sampled data is spell accuracy 0.7580645161290323, grammar accuracy 0.7446808510638298 and randomstate is35

In [72]:
X_train, X_test, y_train_spelling, y_test_spelling, y_train_grammar, y_test_grammar = train_test_split(
    X, y_spelling, y_grammar, test_size=0.3, random_state=35)

In [73]:
knn_spelling = KNeighborsClassifier()
knn_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
knn_grammar = KNeighborsClassifier()
knn_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
y_pred_spelling = knn_spelling.predict(X_test)
y_pred_grammar = knn_grammar.predict(X_test)
    
acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
print(acc_spell)    
acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
print(acc_grammar)

0.6833333333333333
0.5333333333333333

In [74]:
dtc_spelling = DecisionTreeClassifier()
dtc_spelling.fit(X_train, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
dtc_grammar = DecisionTreeClassifier()
dtc_grammar.fit(X_train, y_train_grammar)

# Predict on the test set
y_pred_spelling = dtc_spelling.predict(X_test)
y_pred_grammar = dtc_grammar.predict(X_test)
    
acc_spell=accuracy_score(y_test_spelling, y_pred_spelling)
print(acc_spell)    
acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar)
print(acc_grammar)

0.5833333333333334
0.5666666666666667

In [82]:
X_train_spelling, X_test_spelling, y_train_spelling, y_test_spelling = train_test_split(X_sampled_spelling, y_spelling_sampled, test_size=0.2, random_state=50)

# Split for grammar task
X_train_grammar, X_test_grammar, y_train_grammar, y_test_grammar = train_test_split(X_sampled_grammar, y_grammar_sampled, test_size=0.2, random_state=50)


# Initialize and fit RandomForestClassifier
dtc2_spelling = DecisionTreeClassifier(criterion='entropy', max_depth= 30, min_samples_leaf= 4, min_samples_split= 10)
dtc2_spelling.fit(X_train_spelling, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
dtc2_grammar= DecisionTreeClassifier()
dtc2_grammar= dtc2_grammar.fit(X_train_grammar, y_train_grammar)

# Predict on the test set
y_pred_spelling1 = dtc2_spelling.predict(X_test_spelling)
y_pred_grammar1 = dtc2_grammar.predict(X_test_grammar)
    
acc_spell=accuracy_score(y_test_spelling, y_pred_spelling1)
print(acc_spell)
acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar1)
print(acc_grammar)

0.7741935483870968
0.7021276595744681

In [102]:
maxACC_spell=0
maxACC_gram=0
maxRs=0
for i in range(1,400):
    X_train_spelling, X_test_spelling, y_train_spelling, y_test_spelling = train_test_split(X_sampled_spelling, y_spelling_sampled, test_size=0.2, random_state=i)

# Split for grammar task
    X_train_grammar, X_test_grammar, y_train_grammar, y_test_grammar = train_test_split(X_sampled_grammar, y_grammar_sampled, test_size=0.2, random_state=i)


# Initialize and fit RandomForestClassifier
    rf2_spelling = RandomForestClassifier()
    rf2_spelling.fit(X_train_spelling, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
    rf2_grammar= RandomForestClassifier()
    rf2_grammar= rf2_grammar.fit(X_train_grammar, y_train_grammar)

# Predict on the test set
    y_pred_spelling2 = rf2_spelling.predict(X_test_spelling)
    y_pred_grammar2= rf2_grammar.predict(X_test_grammar)
    
    acc_spell=accuracy_score(y_test_spelling, y_pred_spelling2)
    acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar2)
    
    if acc_grammar>maxACC_gram and acc_spell>maxACC_spell:
        maxACC_spell=acc_spell
        maxACC_gram=acc_grammar
        maxRs=i
print(f'Best Accuracy for grammar:{maxACC_spell} and spelling{maxACC_gram} with randomstate{maxRs}')

Best Accuracy for grammar:0.8387096774193549 and spelling0.6595744680851063 with randomstate202

In [103]:
X_train_spelling, X_test_spelling, y_train_spelling, y_test_spelling = train_test_split(X_sampled_spelling, y_spelling_sampled, test_size=0.2, random_state=202)

# Split for grammar task
X_train_grammar, X_test_grammar, y_train_grammar, y_test_grammar = train_test_split(X_sampled_grammar, y_grammar_sampled, test_size=0.2, random_state=202)


# Initialize and fit RandomForestClassifier
rf2_spelling = RandomForestClassifier()
rf2_spelling.fit(X_train_spelling, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
rf2_grammar= RandomForestClassifier()
rf2_grammar= rf2_grammar.fit(X_train_grammar, y_train_grammar)

# Predict on the test set
y_pred_spelling2 = rf2_spelling.predict(X_test_spelling)
y_pred_grammar2= rf2_grammar.predict(X_test_grammar)
    
acc_spell=accuracy_score(y_test_spelling, y_pred_spelling2)
print(acc_spell)
acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar2)
print(acc_grammar)

0.8064516129032258
0.5957446808510638

In [105]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import classification_report


# Define the parameter grid for RandomizedSearchCV
param_grid = {
    'n_estimators': [100, 200, 300, 400, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth': [10, 20, 30, 40, 50, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}


# Initialize RandomizedSearchCV
random_search1 = RandomizedSearchCV(
    estimator=rf2_spelling, param_distributions=param_grid,
    n_iter=100, cv=3, verbose=2, random_state=202, n_jobs=-1
)

# Fit the model for grammar errors
random_search1.fit(X_train_spelling, y_train_spelling)

# Get the best parameters for grammar error detection
best_params_spelling = random_search1.best_params_
print(f"Best parameters for spellingerror detection: {best_params_spelling}")

# Evaluate the grammar error model
random_search1 = RandomizedSearchCV(
    estimator=rf2_spelling, param_distributions=param_grid,
    n_iter=100, cv=3, verbose=2, random_state=202, n_jobs=-1
)


# Initialize RandomizedSearchCV
random_search2 = RandomizedSearchCV(
    estimator=rf2_grammar, param_distributions=param_grid,
    n_iter=100, cv=3, verbose=2, random_state=42, n_jobs=-1
)
# Fit the model for grammar errors
random_search2.fit(X_train_grammar, y_train_grammar)

# Get the best parameters for grammar error detection
best_params_grammar = random_search2.best_params_
print(f"Best parameters for grammar error detection: {best_params_grammar}")

Fitting 3 folds for each of 100 candidates, totalling 300 fits

C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
84 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
72 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [0.69266285 0.69261267 0.68041754        nan        nan 0.71750477
        nan        nan 0.70927431        nan        nan        nan
 0.688648   0.6928636  0.71328917 0.71333936 0.71750477 0.70084312
 0.69697882        nan 0.70109405 0.72563485 0.70094349 0.69682826
 0.70520927        nan 0.68874837        nan 0.70089331        nan
 0.69677808        nan 0.70094349        nan        nan        nan
 0.70922413 0.69687845 0.69271304 0.70084312        nan 0.70505872
 0.68869818 0.7174044  0.71750477 0.7051089  0.70079293 0.70495835
 0.70927431 0.71328917 0.7174044  0.68453277 0.69687845        nan
        nan        nan 0.70094349 0.69682826 0.71323898 0.70927431
 0.70515909 0.70922413 0.69697882 0.68051792        nan 0.70505872
 0.70505872 0.688648          nan 0.70099368 0.71735421 0.68448259
        nan 0.70922413        nan        nan 0.70099368 0.70912376
 0.70094349        nan 0.70099368 0.70094349 0.69697882 0.72151962
 0.68874837 0.70922413 0.68448259 0.69266285 0.70505872        nan
 0.71333936        nan        nan 0.69271304 0.70917394 0.70917394
 0.69692864 0.69682826 0.71338954 0.70500853]
  warnings.warn(

Best parameters for spellingerror detection: {'n_estimators': 300, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 20, 'bootstrap': False}
Fitting 3 folds for each of 100 candidates, totalling 300 fits

C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
126 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
92 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
34 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan 0.53481403 0.51886127        nan 0.5510312  0.52979023
 0.56187203        nan 0.52952582        nan 0.49717962        nan
        nan        nan        nan 0.51322052        nan 0.52397321
        nan        nan        nan 0.51330866 0.50775604        nan
        nan 0.52952582 0.50282038 0.52423762 0.52934955 0.52961396
 0.51859686        nan 0.50255597        nan        nan 0.52952582
 0.57271285 0.54556672 0.54027851        nan 0.57808919        nan
        nan 0.52432575 0.52987837 0.50793231 0.5026441         nan
        nan        nan        nan 0.5297021         nan        nan
 0.54565486 0.55649568 0.53507844 0.57271285        nan 0.49162701
 0.52934955        nan 0.51330866        nan        nan 0.49709149
 0.56733651        nan 0.56178389 0.54565486 0.51859686 0.5510312
 0.58355368        nan 0.52943769 0.51877314        nan        nan
 0.52388507        nan 0.49162701        nan 0.54574299        nan
 0.56733651        nan 0.51859686 0.51348493 0.56196016        nan
 0.52414948 0.50793231 0.57808919 0.50273224 0.54027851 0.51886127
        nan        nan 0.53507844        nan]
  warnings.warn(

Best parameters for grammar error detection: {'n_estimators': 300, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': None, 'bootstrap': True}

In [106]:
X_train_spelling, X_test_spelling, y_train_spelling, y_test_spelling = train_test_split(X_sampled_spelling, y_spelling_sampled, test_size=0.2, random_state=202)

# Split for grammar task
X_train_grammar, X_test_grammar, y_train_grammar, y_test_grammar = train_test_split(X_sampled_grammar, y_grammar_sampled, test_size=0.2, random_state=202)


# Initialize and fit RandomForestClassifier
rf2_spelling = RandomForestClassifier(n_estimators=300,min_samples_split= 5, min_samples_leaf= 1, max_features= 'log2', max_depth= None, bootstrap= True)
rf2_spelling.fit(X_train_spelling, y_train_spelling)

# Train a Logistic Regression model for grammar error detection
rf2_grammar= RandomForestClassifier(n_estimators=300, min_samples_split=10, min_samples_leaf=2, max_features='sqrt', max_depth=20, bootstrap=False)
rf2_grammar= rf2_grammar.fit(X_train_grammar, y_train_grammar)

# Predict on the test set
y_pred_spelling2 = rf2_spelling.predict(X_test_spelling)
y_pred_grammar2= rf2_grammar.predict(X_test_grammar)
    
acc_spell=accuracy_score(y_test_spelling, y_pred_spelling2)
print(acc_spell)
acc_grammar=accuracy_score(y_test_grammar, y_pred_grammar2)
print(acc_grammar)

0.8387096774193549
0.6382978723404256

In [65]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}


# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=knn_grammar, param_grid=param_grid, cv=5, scoring='accuracy')

# Perform grid search
grid_search.fit(X_train, y_train_grammar)

# Get the best parameters and the best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print(f"Best parameters found: {best_params}")
print(f"Best cross-validation accuracy: {best_score}")

# Evaluate the best model on the test set
best_knn = grid_search.best_estimator_
test_accuracy = best_knn.score(X_test, y_test_grammar)
print(f"Test set accuracy of best model: {test_accuracy}")

Best parameters found: {'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'uniform'}
Best cross-validation accuracy: 0.5625
Test set accuracy of best model: 0.5

In [80]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold

# Assuming X_train, X_test, y_train, y_test are already defined
# X_train, X_test should contain your feature vectors (after text processing)
# y_train, y_test should contain your target labels

# Define Decision Tree classifier
# Define grid of hyperparameters
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Setup cross-validation
k_fold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Perform grid search
grid_search = GridSearchCV(estimator=dtc2_spelling, param_grid=param_grid, cv=k_fold, scoring='accuracy')
grid_search.fit(X_train_spelling, y_train_spelling)

# Print best parameters and evaluate on test set
print("Best Parameters:", grid_search.best_params_)
best_model = grid_search.best_estimator_
test_accuracy = best_model.score(X_test_spelling, y_test_spelling)
print("Test Accuracy:", test_accuracy)

grid_search = GridSearchCV(estimator=dtc2_grammar, param_grid=param_grid, cv=k_fold, scoring='accuracy')
grid_search.fit(X_train_grammar, y_train_grammar)

print("Best Parameters:", grid_search.best_params_)
best_model1 = grid_search.best_estimator_
test_accuracy2 = best_model1.score(X_test_grammar, y_test_grammar)
print("Test Accuracy:", test_accuracy2)

Best Parameters: {'criterion': 'entropy', 'max_depth': 30, 'min_samples_leaf': 4, 'min_samples_split': 10}
Test Accuracy: 0.8064516129032258
Best Parameters: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 2}
Test Accuracy: 0.6382978723404256

In [66]:
import joblib

In [107]:
joblib.dump(dtc2_grammar,'grammar_detection.pkl')
joblib.dump(rf2_spelling,'spelling_detection.pkl')

['spelling_detection.pkl']

In [108]:
model1=joblib.load('grammar_detection.pkl')
pred_gram=model1.predict(X_test_grammar)
model2=joblib.load('spelling_detection.pkl')
pred_spell=model2.predict(X_test_spelling)

In [109]:
b=np.array(y_test_spelling)
a=np.array(y_test_grammar)
df=pd.DataFrame()
df1=pd.DataFrame()
df1['Original_gram']=a
df1['Predicted_gram']=pred_gram
df['Original_spell']=b
df['Predicted_spell']=pred_spell

In [110]:
df1

    Original_gram  Predicted_gram
0               1               1
1               0               0
2               0               0
3               1               1
4               1               1
5               0               0
6               0               0
7               1               0
8               0               0
9               0               0
10              0               0
11              1               1
12              0               0
13              0               1
14              0               0
15              1               0
16              0               0
17              1               1
18              1               0
19              0               0
20              0               0
21              0               0
22              1               1
23              0               0
24              1               1
25              0               1
26              1               1
27              0               0
28              1               1
29              1               0
30              0               0
31              0               0
32              0               0
33              1               1
34              0               0
35              1               0
36              1               1
37              0               0
38              0               0
39              1               1
40              1               1
41              1               1
42              1               1
43              1               1
44              1               1
45              1               1
46              1               1

In [111]:
df

    Original_spell  Predicted_spell
0                0                0
1                0                0
2                1                1
3                0                1
4                1                0
..             ...              ...
57               1                1
58               1                1
59               1                1
60               1                1
61               1                1

[62 rows x 2 columns]

In [112]:
# Assuming you have your new sentences in a list or array
new_sentences = [
    "He plays the piano beautiful.",
    "We visited there grandparent's house last summer.",
    "She writed a poem for her teacher.",
    "I have an apple in my bag.",
    "They're going to the park next weekend."
]

# Preprocess your new sentences (tokenization, vectorization, etc.)
# Ensure to transform your new sentences into the same format as your training data

# Example: Assuming X_new_sentences contains the preprocessed new sentences

# Predict grammar errors
predictions_grammar = model1.predict(X_test_grammar)

# Predict spelling errors
predictions_spelling = model2.predict(X_test_spelling)

# Print or handle the predictions
for sentence, pred_grammar, pred_spelling in zip(new_sentences, predictions_grammar, predictions_spelling):
    if pred_grammar == 1:
        print(f"Grammar error detected in sentence: '{sentence}'")
        # Implement logic to handle or correct grammar errors
    if pred_spelling == 1:
        print(f"Spelling error detected in sentence: '{sentence}'")
        # Implement logic to handle or correct spelling errors
    if pred_grammar == 0 and pred_spelling == 0:
        print(f"No errors detected in sentence: '{sentence}'")
        # Proceed with normal processing

Grammar error detected in sentence: 'He plays the piano beautiful.'
No errors detected in sentence: 'We visited there grandparent's house last summer.'
Spelling error detected in sentence: 'She writed a poem for her teacher.'
Grammar error detected in sentence: 'I have an apple in my bag.'
Spelling error detected in sentence: 'I have an apple in my bag.'
Grammar error detected in sentence: 'They're going to the park next weekend.'

In [113]:
import pandas as pd
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report

# Correct the labels based on feedback
corrected_data = pd.DataFrame({
    "sentences": [
        "He plays the piano beautifully.",
        "We visited their grandparent's house last summer.",
        "She wrote a poem for her teacher.",
        "I have an apple in my bag.",
        "They're going to the park next weekend.",
        "He is going to the store.",
        "I saw that movie yesterday.",
        "She wrote a letter to her friend.",
        "They are visiting their home.",
        "She does not like how to write the novels."
    ],
    "grammar label": [
        0,  # Corrected
        0,  # Corrected
        0,  # Corrected
        0,  # No error
        0,  # No error
        0,  # Corrected
        0,  # Corrected
        0,  # Corrected
        0,  # Corrected
        0   # Corrected
    ],
    "spelling label": [
        0,  # Corrected
        0,  # Corrected
        0,  # Corrected
        0,  # No error
        0,  # No error
        0,  # No error
        0,  # No error
        0,  # No error
        0,  # No error
        0   # No error
    ]
})

# Split the dataset into training and test sets
sentences_train, sentences_test, labels_grammar_train, labels_grammar_test, labels_spelling_train, labels_spelling_test = train_test_split(
    corrected_data['sentences'], corrected_data['grammar label'], corrected_data['spelling label'], test_size=0.2, random_state=42)

# Vectorize the sentences using TF-IDF
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(sentences_train)
X_test = vectorizer.transform(sentences_test)

# Define the parameter grid for RandomizedSearchCV
param_grid = {
    'n_estimators': [100, 200, 300, 400, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth': [10, 20, 30, 40, 50, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

# Initialize the RandomForestClassifier
rf_classifier = RandomForestClassifier()

# Initialize RandomizedSearchCV for grammar errors
random_search_grammar = RandomizedSearchCV(
    estimator=rf_classifier, param_distributions=param_grid,
    n_iter=100, cv=3, verbose=2, random_state=42, n_jobs=-1
)

# Fit the model for grammar errors
random_search_grammar.fit(X_train, labels_grammar_train)

# Get the best parameters for grammar error detection
best_params_grammar = random_search_grammar.best_params_

# Initialize RandomizedSearchCV for spelling errors
random_search_spelling = RandomizedSearchCV(
    estimator=rf_classifier, param_distributions=param_grid,
    n_iter=100, cv=3, verbose=2, random_state=42, n_jobs=-1
)

# Fit the model for spelling errors
random_search_spelling.fit(X_train, labels_spelling_train)

# Get the best parameters for spelling error detection
best_params_spelling = random_search_spelling.best_params_

# Evaluate the grammar error model
predictions_grammar = random_search_grammar.predict(X_test)
grammar_report = classification_report(labels_grammar_test, predictions_grammar)

# Evaluate the spelling error model
predictions_spelling = random_search_spelling.predict(X_test)
spelling_report = classification_report(labels_spelling_test, predictions_spelling)

print("Best parameters for grammar error detection:", best_params_grammar)
print("Classification report for grammar error detection:\n", grammar_report)
print("Best parameters for spelling error detection:", best_params_spelling)
print("Classification report for spelling error detection:\n", spelling_report)

Fitting 3 folds for each of 100 candidates, totalling 300 fits

C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
126 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
99 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
27 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [nan  1.  1. nan  1.  1.  1. nan  1. nan  1. nan nan nan nan  1. nan  1.
 nan nan nan  1.  1. nan nan  1.  1.  1.  1.  1.  1. nan  1. nan nan  1.
  1.  1.  1. nan  1. nan nan  1.  1.  1.  1. nan nan nan nan  1. nan nan
  1.  1.  1.  1. nan  1.  1. nan  1. nan nan  1.  1. nan  1.  1.  1.  1.
  1. nan  1.  1. nan nan  1. nan  1. nan  1. nan  1. nan  1.  1.  1. nan
  1.  1.  1.  1.  1.  1. nan nan  1. nan]
  warnings.warn(

Fitting 3 folds for each of 100 candidates, totalling 300 fits

C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
126 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
111 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ganes\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ganes\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [nan  1.  1. nan  1.  1.  1. nan  1. nan  1. nan nan nan nan  1. nan  1.
 nan nan nan  1.  1. nan nan  1.  1.  1.  1.  1.  1. nan  1. nan nan  1.
  1.  1.  1. nan  1. nan nan  1.  1.  1.  1. nan nan nan nan  1. nan nan
  1.  1.  1.  1. nan  1.  1. nan  1. nan nan  1.  1. nan  1.  1.  1.  1.
  1. nan  1.  1. nan nan  1. nan  1. nan  1. nan  1. nan  1.  1.  1. nan
  1.  1.  1.  1.  1.  1. nan nan  1. nan]
  warnings.warn(

Best parameters for grammar error detection: {'n_estimators': 500, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 40, 'bootstrap': True}
Classification report for grammar error detection:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

Best parameters for spelling error detection: {'n_estimators': 500, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 40, 'bootstrap': True}
Classification report for spelling error detection:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

In [118]:
sentences_train, sentences_test, labels_grammar_train, labels_grammar_test, labels_spelling_train, labels_spelling_test = train_test_split(
    corrected_data['sentences'], corrected_data['grammar label'], corrected_data['spelling label'], test_size=0.2, random_state=42)

# Vectorize the sentences using TF-IDF
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(sentences_train)
X_test = vectorizer.transform(sentences_test)


# Initialize and fit RandomForestClassifier
rf3_spelling = RandomForestClassifier(n_estimators=300,min_samples_split= 5, min_samples_leaf= 2, max_features= 'sqrt', max_depth= 40, bootstrap= True)
rf3_spelling.fit(X_train, labels_spelling_train)

# Train a Logistic Regression model for grammar error detection
rf3_grammar= RandomForestClassifier(n_estimators=500, min_samples_split=10, min_samples_leaf=2, max_features='sqrt', max_depth=40, bootstrap=True)
rf3_grammar.fit(X_train, labels_grammar_train)

# Predict on the test set
y_pred_spelling3 = rf3_spelling.predict(X_test)
y_pred_grammar3= rf3_grammar.predict(X_test)
    
acc_spell1=accuracy_score(labels_spelling_test, y_pred_spelling3)
print(acc_spell1)
acc_grammar1=accuracy_score(labels_spelling_test, y_pred_grammar3)
print(acc_grammar1)

1.0
1.0

In [128]:
import joblib

joblib.dump(rf3_grammar,'grammar_detection1.pkl')
joblib.dump(rf3_spelling,'spelling_detection1.pkl')

['spelling_detection1.pkl']

In [129]:
model3=joblib.load('grammar_detection1.pkl')
pred_gram=model3.predict(X_test)
model4=joblib.load('spelling_detection1.pkl')
pred_spell=model4.predict(X_test)

In [130]:
# Assuming you have your new sentences in a list or array
new_sentences = [
    "He plays the piano beautiful.",
    "We visited there grandparent's house last summer.",
    "She writed a poem for her teacher.",
    "I have an apple in my bag.",
    "They're going to the park next weekend."
]

# Preprocess your new sentences (tokenization, vectorization, etc.)
# Ensure to transform your new sentences into the same format as your training data

# Example: Assuming X_new_sentences contains the preprocessed new sentences

# Predict grammar errors
predictions_grammar = model3.predict(X_test)

# Predict spelling errors
predictions_spelling = model4.predict(X_test)

# Print or handle the predictions
for sentence, pred_grammar, pred_spelling in zip(new_sentences, predictions_grammar, predictions_spelling):
    if pred_grammar == 1:
        print(f"Grammar error detected in sentence: '{sentence}'")
        # Implement logic to handle or correct grammar errors
    if pred_spelling == 1:
        print(f"Spelling error detected in sentence: '{sentence}'")
        # Implement logic to handle or correct spelling errors
    if pred_grammar == 0 and pred_spelling == 0:
        print(f"No errors detected in sentence: '{sentence}'")
        # Proceed with normal processing

No errors detected in sentence: 'He plays the piano beautiful.'
No errors detected in sentence: 'We visited there grandparent's house last summer.'